#cd libxml2-2.7.8
#emmake make
#cd ..

# Note: libz.a generated by EM_SAVE_DIR=1 python tests/runner.py test_zlib

# Test:
#~/Dev/emscripten/emcc -O2 libxml2-2.7.8/xmllint.o libxml2-2.7.8/.libs/libxml2.a libz.a -o xmllint.test.js --embed-file test.xml --embed-file test.xsd
# js xmllint.test.js --noout --schema test.xsd test.xml

# Production
sudo emcc -O1 --minify 1 -s ASM_JS=0 -s SAFE_HEAP=1 libxml2-2.7.8/xmllint.o libxml2-2.7.8/.libs/libxml2.a libz.a -o xmllint.raw.js --pre-js pre.js
#echo "function validateXML(Module) {" > xmllint.js
#echo "  Module['preRun'] = function(){" >> xmllint.js
#echo "    FS.createDataFile('/', Module['title'], Module['intArrayFromString'](Module['xml']), true, true);" >> xmllint.js
#echo "    FS.createDataFile('/', 'test.rng', Module['intArrayFromString'](Module['schema']), true, true);" >> xmllint.js
#echo "  };" >> xmllint.js
#echo "  Module.arguments = ['--noout', '--relaxng', 'test.rng', Module['title']];" >> xmllint.js
cat xmllint.raw.js >> xmllint.js
echo "  return Module.return;" >> xmllint.js
echo "}  " >> xmllint.js
